<?php
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

// Start counting from 0
$sum = 0;

// Set the initial prev & old terms
$prev = 1; $old = 2;

// Prevent the sum from exceeding 4,000,000.
while ($prev < 4000000)
{
  // Store the sum of the previous two terms.
  $cur = $prev+$old;

  // Update the previous two terms.
  $prev = $old;
  $old = $cur;

  // Check that the previous term is even.
  if($prev%2 == 0)
  {
    $sum += $prev;
  }
}

echo $sum;